In [1]:
# Blue outlines means Command mode
# And Green means Edit Mode(Where we write code)
2+3

5

In [5]:
# Press b to add shell
import numpy as np

In [4]:
# Ctrl+Enter  ----> to run code
# Shift+Enter   -----> run code + add shell
# Esc ----> to go command mode
# press d two times in command mode -----> to delete shell

# press 1 in command mode ----> to add notes or give headings, after write content in heading press Shift+Enter
# If we write ## two times our heading size will be redducrd, we can also write html code in it

# This is Heading

## This is Heading
<h1>This is also Heading</h1>

In [6]:
# In this Chapter You will learn about
# How to create Numpy Arrays?
# How to create Numpy Arrays using Functions?
# How to reshape data?
# what is -1?
# Generate same random numbers?
# Indexing and slicing of 1-d and 2-d arrays?
# View vs Copy
# Conditional Selection
# Numpy Operation
# Numpy Axis
# Shuffle and Uniqe
# Stacking
# Excercise
# Comapre Numpy Array vs Python lists


In [8]:
# Numpy Inro
# It is Python Library designed for scientific computation
# Numpy arrays are the main way to use Numpy Library
# In this course we will learn how to work with multi dimensional arrays using numpy
# It is really really compare to  ordinary python lists
# it is fast beccause it has binding with c programming langauge

# 1-d Array ---> vector
# 2-d Array ---> matrix
# n-d Array ---> tensor


# Create NumPy Arrays

In [9]:
import numpy as np

In [20]:
nums_1d=[1,2,3]

In [21]:
nums_1d=np.array(nums_1)

In [29]:
nums_1d

array([1, 2, 3])

In [30]:
nums_2d=[[1,2,3],[4,5,6]]

In [31]:
nums_2d=np.array(nums_2d)

In [32]:
nums_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
nums_3d=[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]

In [41]:
nums_3d=np.array(nums_3d)

In [42]:
nums_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [43]:
nums.ndim     # to check type of array

1

In [45]:
nums_1d.ndim

1

In [46]:
nums_2d.ndim

2

In [47]:
nums_3d.ndim

3

In [48]:
nums_1d.shape                # it will return tuple which tell me  no of rows and column  and three elements in array

(3,)

In [49]:
nums_2d.shape                # 2 row and 3 column

(2, 3)

In [51]:
nums_3d.shape             

(2, 2, 3)

In [52]:
# we can store many data which have different data types but in numpy array we can store data which have same data type

In [56]:
nums_1=[1,2,3.0]
nums_1=np.array(nums_1)

In [57]:
nums_1               # here we can see that all values changed in float

array([1., 2., 3.])

In [58]:
nums_2=[1,2,'3.0']
nums_2=np.array(nums_2)
nums_2                                             # all values changed in string

array(['1', '2', '3.0'], dtype='<U11')

In [61]:
 nums_2.dtype

dtype('<U11')

#  

#  

#   

# Create Numpy Arrays using NumPy methods(functions)    

In [66]:
import numpy as np
# zeros, ones, eye, diag, randint, rand, randn

### zeros function

In [64]:
arr=np.zeros(5)                       # it will give us array which has five element whose values are 0
arr

array([0., 0., 0., 0., 0.])

In [65]:
arr_1=np.zeros((2,3))                     # 2-d matrix which has 2 rows and 3 columns
arr_1

array([[0., 0., 0.],
       [0., 0., 0.]])

### ones function

In [67]:
arr_2=np.ones((2,3))
arr_2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
arr_21=np.ones(4)
arr_21

array([1., 1., 1., 1.])

### Eye function

In [69]:
arr_3=np.eye(4)                  # it's fpr diagonal( give me 2-d 4 row's array which diagonal's element has 1 value and others has 0 value)
arr_3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
arr_31=np.eye(3,4)
arr_31

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Diag Function


In [72]:
array_4=np.diag([1,2,3,4])             # this func takes input as list
array_4                     # print list in diag

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [73]:
np.diag(array_4)              # to get diagonal values of array

array([1, 2, 3, 4])

### Randint Function

In [74]:
rand_arr=np.random.randint(1,15,4)                  # TO generate random number
rand_arr                                # i will get 4 integer between 1-14(not 15)

array([4, 9, 1, 8])

### Rand Function

In [75]:
rand_arr1=np.random.rand(4)                         # it will give me 4 values betwenn 0-1
rand_arr1

array([0.67368376, 0.94871432, 0.28522347, 0.5972952 ])

In [77]:
rand_arr11=np.random.rand(10)
rand_arr11

array([0.21069067, 0.19019137, 0.47660487, 0.9737893 , 0.43535482,
       0.14977263, 0.72958621, 0.13994356, 0.15227852, 0.44945457])

In [78]:
rand_arr111=np.random.rand(2,3)        # 2 rows 3 columns
rand_arr111

array([[0.83179468, 0.52546754, 0.69409891],
       [0.79029651, 0.75217621, 0.80104494]])

### Randn Function

In [79]:
rand_arr4=np.random.randn(4)             # o/p will be nearby zero and number always from standard norml distibution
rand_arr4

array([-0.08927515,  0.78754029,  0.84621882, -0.31203215])

In [81]:
rand_arr41=np.random.randn(40)             # o/p will be nearby zero and number always from standard norml distibution
rand_arr41

array([ 0.58193045,  0.56778893,  1.29678222,  0.3961833 ,  1.4295986 ,
       -0.0637264 , -0.61739458,  0.32400894,  1.30652534,  1.41060943,
       -0.52758876, -0.25881901, -0.99781424, -0.37300447, -1.10325289,
        0.68439183, -0.33712881,  1.26917696, -0.22261233, -0.52410266,
        0.73061891,  1.01463495, -0.95801055,  1.53139419, -0.262319  ,
       -0.3766963 ,  1.0787755 ,  0.83885655,  0.34256333, -1.21338693,
       -2.11804151,  0.03793564, -2.56075384, -0.12396042, -0.03450678,
       -0.94323976, -0.08919332,  1.85188542, -0.61835061,  0.22548281])

In [82]:
rand_arr41=np.random.randn(40)      
np.mean(rand_arr41)                    # for average # average also nearby zero

0.11829961817325003

In [83]:
rand_arr411=np.random.randn(15000)      
np.mean(rand_arr411)             # mean always nearby zero

0.0028000817071400547

#  

#  

#    

# Reshaping of Data 

In [84]:
import numpy as np

In [90]:
arrr=np.random.randint(1,100,20)
arrr

array([25, 48, 22, 75, 18, 11, 72, 37, 71,  8, 45, 14, 22,  6, 10, 17, 84,
       85, 86, 97])

In [91]:
arrr.ndim

1

In [92]:
arrr.shape                  # single 1-d array and 20 elements

(20,)

##### reshape means convert 1-d arry in 2-d or 3-d array

In [95]:
arrr=arrr.reshape(2,10)           # 2*10=20      multiplication is equla to no of elements in array
arrr                        # so i got 2-d array which has two lists of 10 elements(means 2 row 10 columns)

array([[25, 48, 22, 75, 18, 11, 72, 37, 71,  8],
       [45, 14, 22,  6, 10, 17, 84, 85, 86, 97]])

In [96]:
arrr.shape

(2, 10)

In [97]:
arrr.ndim

2

In [99]:
arrr=arrr.reshape(20)       # convert 2-d to 1-d
arrr

array([25, 48, 22, 75, 18, 11, 72, 37, 71,  8, 45, 14, 22,  6, 10, 17, 84,
       85, 86, 97])

In [101]:
arrr1=np.random.randint(1,100,50)
arrr1

array([ 9,  7, 32, 38, 39, 44, 91, 44,  3,  1, 99, 77, 36, 83, 48, 82, 82,
       30, 42, 56, 97, 45, 46,  3, 63, 13, 80, 31, 63, 23, 60, 88, 64, 98,
       80, 57,  8, 36, 71, 68,  7, 26, 28,  7,  1, 40, 32, 99, 58, 22])

In [102]:
arrr1=arrr1.reshape(10,5)
arrr1

array([[ 9,  7, 32, 38, 39],
       [44, 91, 44,  3,  1],
       [99, 77, 36, 83, 48],
       [82, 82, 30, 42, 56],
       [97, 45, 46,  3, 63],
       [13, 80, 31, 63, 23],
       [60, 88, 64, 98, 80],
       [57,  8, 36, 71, 68],
       [ 7, 26, 28,  7,  1],
       [40, 32, 99, 58, 22]])

In [104]:
arrr1=arrr1.reshape(2,5,5)             # 2*5*5=50
arrr1                        # two array five rows fivve columns

array([[[ 9,  7, 32, 38, 39],
        [44, 91, 44,  3,  1],
        [99, 77, 36, 83, 48],
        [82, 82, 30, 42, 56],
        [97, 45, 46,  3, 63]],

       [[13, 80, 31, 63, 23],
        [60, 88, 64, 98, 80],
        [57,  8, 36, 71, 68],
        [ 7, 26, 28,  7,  1],
        [40, 32, 99, 58, 22]]])

In [106]:
arrr1=arrr1.reshape(5,2,5)             # 2*5*5=50
arrr1                       # (arrays, rows, columns)

array([[[ 9,  7, 32, 38, 39],
        [44, 91, 44,  3,  1]],

       [[99, 77, 36, 83, 48],
        [82, 82, 30, 42, 56]],

       [[97, 45, 46,  3, 63],
        [13, 80, 31, 63, 23]],

       [[60, 88, 64, 98, 80],
        [57,  8, 36, 71, 68]],

       [[ 7, 26, 28,  7,  1],
        [40, 32, 99, 58, 22]]])

#  

#   

#     

#  what is -1 in reshape() 

In [107]:
import numpy as np

In [108]:
arry=np.arange(1,11)
arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arry.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [112]:
arry.reshape(2,-1)                           # -1 will consider value automatically for 2*x=10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [113]:
arry.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [115]:
arry1=np.arange(1,111)
arry1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [116]:
arry1.size

110

In [117]:
arry1.reshape(5,-1)          # i want 5 rows

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [118]:
arry1.reshape(-1,5)           # i want 5 columns

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

#   

#   

#     

#   

# Generate Same Random Numbers (Seed Funcions)

In [1]:
import numpy as np

In [4]:
arr=np.random.randint(1,101,10)
arr                                        # when we run this we will get 10 random numbers, but when we will generate our random number second time we will get different numbers compared to first one,
                                                    # we can overcome this problem using seed function

array([ 3, 61,  2, 24, 24, 70, 69, 97, 49, 75])

In [12]:
np.random.seed(12)                           # if i will change number in seed() i will get different output.
arr1=np.random.randint(1,101,10)
arr1                                 # generate 10 random numbers all the time same(on all machine)

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [11]:
arr1.size

10

In [14]:
np.random.seed(12)                           
arr1=np.random.randint(1,101,10).reshape(2,5)
arr1                                 

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50]])

#  

#    

#    `

# Indexing and Slicing of 1-d Array

In [15]:
import numpy as np

In [17]:
ar_ray=np.array([5,10,15,20,25])
ar_ray

array([ 5, 10, 15, 20, 25])

#### slicing in 1-d array is same as list in python

In [20]:
ar_ray[0]

5

In [21]:
ar_ray[4]

25

In [22]:
ar_ray[::1]

array([ 5, 10, 15, 20, 25])

In [23]:
ar_ray[::-1]

array([25, 20, 15, 10,  5])

In [24]:
ar_ray[2:5]

array([15, 20, 25])

In [25]:
ar_ray[-1:4]

array([], dtype=int32)

In [26]:
ar_ray[-1]

25

In [28]:
ar_ray[3::-1]

array([20, 15, 10,  5])

In [29]:
ar_ray[:]

array([ 5, 10, 15, 20, 25])

In [30]:
ar_ray[:-1]

array([ 5, 10, 15, 20])

 #     

#    






#    

#   indexing and slicing in 2-d matrix Array 

#### Create 2-d Array

In [34]:
import numpy as np

In [33]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Indexing using double bracket notation

In [35]:
matrix[0][1]

2

In [36]:
matrix[1][1]

5

In [37]:
matrix[2][0]                          # [row][column]

7

#### Indexing using single bracket notation (Recommended)

In [38]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
 matrix[0,1]

2

In [40]:
 matrix[2,2]

9

In [42]:
 matrix[1,1]                         # [row, column]

5

#### Slicing using single bracket Notation

In [43]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
matrix[[0,1],[1,1]]

array([2, 5])

In [45]:
# I want 1,2 and 4,5

In [46]:
matrix[:2,:2]

array([[1, 2],
       [4, 5]])

In [48]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [50]:
np.random.seed(123)
matrix2=np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [52]:
matrix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [53]:
matrix2[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

#   

#     

#     

#  

# Numpy : View vs Copy 

In [55]:
import numpy as np

In [59]:
arr=np.array([5,10,15,20,25,30])                          

In [57]:
sliced_arr=arr[2:5]

In [61]:
sliced_arr

array([15, 20, 25])

###### We can do broadcasting in Numpy
###### Brodcasting ----> The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes.

###### arr[:2]=0
###### arr
###### o/p: array([ 0,  0, 15, 20, 25, 30]) -->

In [67]:
sliced_arr[:]=0
arr

array([ 0,  0, 15, 20, 25, 30])

In [68]:
sliced_arr

array([0, 0, 0])

In [64]:
# here we can see that when i changed value of sliced_array of arr, arr's values also changed, so we can say that sliced_arr is element of arr means sliced_ssrr and arr both are on same location this is called view. hence, sliced_arr is view of arr

### Copy

In [70]:
arr1=np.array([5,10,15,20,25,30])      
sliced_arr1=arr1[2:5].copy()
sliced_arr1

array([15, 20, 25])

In [71]:
sliced_arr1[:]=0
sliced_arr1

array([0, 0, 0])

In [72]:
arr1

array([ 5, 10, 15, 20, 25, 30])

#### here, values not changed of arr1

 #     

#          

#             

#     

# Numpy : Conditional Selection

In [73]:
import numpy as np

In [74]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###### I want to chaeck where the values are greater than 4 in a arr

In [75]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

###### it means arr>5 applied on each value

In [76]:
mask=arr>5
arr[mask]

array([ 6,  7,  8,  9, 10])

In [80]:
#  now  i want elements which will less than 4

In [78]:
arr[arr<4]                 # conditional selection

array([1, 2, 3])

In [79]:
# I want even number

In [81]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [82]:
arr[arr==5]

array([5])

In [85]:
arr[arr%2==0]=0

In [86]:
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

#             

#               

#          

#   

# Numpy Operation on Array with Scaler 

In [87]:
import numpy as np

In [103]:
arr=np.array([1,2,3,4])

In [104]:
arr*2

array([2, 4, 6, 8])

In [90]:
arr+5

array([6, 7, 8, 9])

In [91]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [92]:
arr**3

array([ 1,  8, 27, 64], dtype=int32)

In [110]:
arr1=arr.reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [111]:
arr1*2

array([[2, 4],
       [6, 8]])

In [113]:
arr1**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [114]:
arr1+5

array([[6, 7],
       [8, 9]])

In [115]:
arr1/1

array([[1., 2.],
       [3., 4.]])

In [116]:
1/0

ZeroDivisionError: division by zero

In [118]:
arr1/0                         # here im getting warning when i m divide by 0

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

#            

#             

 #             

# Operation on two or more array 

In [119]:
import numpy as np

In [129]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])

In [121]:
array1+array2

array([ 6,  8, 10, 12])

In [123]:
array1*array2

array([ 5, 12, 21, 32])

In [124]:
array_1=np.array([1,2,3,4])
array_2=np.array([5,6,7])

In [127]:
array_1+array_2     # get error because shape is not same

NameError: name 'array_1' is not defined

In [130]:
array1**array2

array([    1,    64,  2187, 65536], dtype=int32)

In [131]:
array1/array2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [132]:
array1*array1

array([ 1,  4,  9, 16])

In [133]:
array1/array1

array([1., 1., 1., 1.])

In [134]:
array1**array1

array([  1,   4,  27, 256], dtype=int32)

In [135]:
array3=np.array([9,10,11,12])

In [136]:
array1**array2+array3

array([   10,    74,  2198, 65548])

In [146]:
np.random.seed(123)
matrix1=np.random.randint(1,12,9).reshape(3,3)
matrix2=np.random.randint(5,15,9).reshape(3,3)

In [147]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [148]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [149]:
 matrix1+matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [150]:
matrix_1=np.random.randint(1,12,10).reshape(2,5)
matrix_1

array([[1, 5, 2, 8, 4],
       [3, 5, 8, 3, 5]])

In [151]:
matrix_1+matrix2

ValueError: operands could not be broadcast together with shapes (2,5) (3,3) 

In [152]:
matrix1*matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [153]:
matrix1.dot(matrix2)               # multiplication of two matrix for linear algebra

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

#       

#     

#     

#    

#  Some more useful NumPy Functions 

In [1]:
import numpy as np

In [2]:
arr=np.array([2,80,1,97,5])

In [4]:
np.min(arr) # to get minimum number

1

In [5]:
np.max(arr) # to get maximum number

97

In [6]:
np.argmin(arr)        # i want to know my minimum number is on which location

2

In [7]:
np.argmax(arr)

3

In [9]:
np.sqrt(arr)                                 # find square root of all elements

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [10]:
np.exp(arr)                    # this give as 2.71828 paower element(like 2.71828**2=7.3890)

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [11]:
2.71828**2

7.3890461584

In [12]:
2.71828**80

5.5403242392390125e+34

In [14]:
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [15]:
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [16]:
np.tan(arr)

array([-2.18503986,  9.00365495,  1.55740772, -0.4103213 , -3.38051501])

In [18]:
np.linspace(1,15,50)                    # this gives me 50 numbers between 1-15(same saperated)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [19]:
np.linspace(1,50,5)       # same saperated

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [20]:
13.25-1

12.25

In [21]:
25.5-13.25

12.25

In [22]:
37.75-25.5

12.25

In [23]:
50-37.75

12.25

In [24]:
arr2=np.array([1,2,3,0])
arr2

array([1, 2, 3, 0])

In [26]:
arr2=np.array([1,2,3,0],dtype='bool')
arr2                                    # for making boolean array(0 value is false and non- zero value is True)

array([ True,  True,  True, False])

In [28]:
arr2=np.array([1,0,1,1],dtype='bool')
arr2

array([ True, False,  True,  True])

In [29]:
for i in arr2:
    print(i)

True
False
True
True


#    

#    

#    

#    

# NumPy Axis

In [30]:
import numpy as np

In [33]:
np.random.seed(123)
matrix=np.random.randint(1,11,9).reshape(3,3)

In [34]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [35]:
np.sum(matrix)

39

In [36]:
matrix.sum()

39

In [37]:
np.min(matrix)

1

In [38]:
np.max(matrix)

10

#  

In [39]:
# row = 1, column = 0   for axis

In [40]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [41]:
# I want [3,2,1]       # 3 is minimum of first row, 2 is minimum of second row and 1 is minimum of third row

In [42]:
np.min(matrix, axis=1)

array([3, 2, 1])

In [43]:
np.min(matrix, axis=0)

array([2, 2, 1])

In [44]:
np.max(matrix,axis=1)

array([ 7, 10,  7])

In [45]:
np.max(matrix, axis=0)

array([ 7,  4, 10])

In [46]:
np.sum(matrix, axis=1)

array([13, 16, 10])

In [47]:
np.sum(matrix, axis=0)

array([12,  9, 18])

In [51]:
np.cumsum(matrix)     # Cumulitive sum(3,3+3,6+7,13+2,.......)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [53]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [49]:
np.cumsum(matrix, axis=0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [55]:
np.cumsum(matrix, axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [57]:
np.prod(matrix, axis=0)          # 3*2*7=42

array([42, 24, 70])

In [58]:
np.prod(matrix)

70560

In [59]:
np.prod(matrix, axis=1)

array([63, 80, 14])

#   




#  












#    

#   

#  Numpy : Shuffle and Unique 

In [60]:
import numpy as np

In [63]:
np.random.seed(123)
arr=np.random.randint(1,15,15)

In [64]:
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [65]:
np.random.shuffle(arr)

In [66]:
arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [67]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [69]:
np.unique(arr).size

10

In [71]:
np.unique(arr, return_index=True, return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

###  I got three arrays
###  1st gives me my unique elements
###  2nd gives me position of elements like 1 is position of 8, 2 is at 1
###  3rd gives me count element like 1 is 1 time only 2 is 3 time, 3 is two time

#    

#     

#    

#    

#   NumPy : Horizontal and Vertical Stacking 

In [72]:
import numpy as np

In [77]:
np.random.seed(123)
matrix1=np.random.randint(1,20,9).reshape(3,3)
matrix2=np.random.randint(20,40,9).reshape(3,3)

In [78]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [79]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [80]:
# Horizontal Stacking -----> conacte two mayrix horizontally(stacking on x axis)

In [81]:
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [82]:
# Vertical Stacking -----> conacte two matrix vertically (stacking on y axis)

In [83]:
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [84]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

In [85]:
array1

array([1, 2, 3])

In [86]:
array2

array([4, 5, 6])

In [87]:
np.hstack((array1,array2))

array([1, 2, 3, 4, 5, 6])

In [89]:
np.vstack((array1,array2))                 # converted in 2-d array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

#     

#   


#    

#    

#  NumPy Exercise 

### Import Numpy library

In [90]:
import numpy as np

### Create an Array using array function

In [93]:
arr1=np.array([3,4,5])
arr1

array([3, 4, 5])

### Create an Array containg number from 20 to 40

In [98]:
arr2=np.arange(20,41)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

### Create an Array which contain 10 elements and every element is 5

In [146]:
arr3=np.arange(0,10)
arr3[:]=5
arr3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [147]:
arr31=np.ones(10)*5
arr31

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Create a 1-d array and then convert it into 3-d array

In [149]:
arr4=np.random.randint(1,20,12)
arr4

array([ 2, 19,  6,  3, 19, 15, 14,  4, 19, 15, 10, 18])

In [150]:
arr4.reshape(2,3,2)

array([[[ 2, 19],
        [ 6,  3],
        [19, 15]],

       [[14,  4],
        [19, 15],
        [10, 18]]])

### Create a 2-d array which contains random 25 numbers between 0 and 1

In [151]:
arr5=np.random.rand(5,5)
arr5

array([[0.56348098, 0.71519128, 0.51761868, 0.35204183, 0.63277886],
       [0.87311902, 0.16788844, 0.98747832, 0.34941493, 0.82620513],
       [0.06546154, 0.00535329, 0.88694465, 0.91131813, 0.19940777],
       [0.02755138, 0.81733492, 0.24182762, 0.05608301, 0.06756083],
       [0.47387186, 0.50942926, 0.41679514, 0.25584293, 0.38151211]])

### create array containing 20 random integer then replace every even number with -1  

###### Exaple
###### array ---> [44,55,12,6,3]
###### o/p: ----> [-1,55,-1,-1,3]

In [153]:
np.random.seed(123)
arr6=np.random.randint(1,200,20)
arr6

array([110, 127,  67,  99,  18,  84, 107, 124,  58,  97, 114, 127,  48,
        74,  33, 175, 112, 154,  84,  79])

In [154]:
arr6[(arr6%2==0)]=-1
arr6

array([ -1, 127,  67,  99,  -1,  -1, 107,  -1,  -1,  97,  -1, 127,  -1,
        -1,  33, 175,  -1,  -1,  -1,  79])

#  

### You Have Matrix
### [[5,10,15,20,25],
### [30,35,40,45,50],
### [55,60,65,70,75],
### [80,85,90,95,100]]



### Extract
### [30,35,40]
### [55,60,65]

In [155]:
matrix=np.array([[5,10,15,20,25],[30,35,40,45,50],[55,60,65,70,75], [80,85,90,95,100]])
matrix

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [156]:
matrix[1][0:3]

array([30, 35, 40])

In [157]:
matrix[2][0:3]

array([55, 60, 65])

In [158]:
matrix[1:3,0:3]

array([[30, 35, 40],
       [55, 60, 65]])

# Concatenate 2 1-d arrays 

In [138]:
arr1=np.random.randint(1,10,3)
arr2=np.random.randint(11,30,5)

In [132]:
arr1

array([9, 2, 1])

In [133]:
arr2

array([14, 12, 15, 18, 17])

In [134]:
np.hstack((arr1,arr2))

array([ 9,  2,  1, 14, 12, 15, 18, 17])

In [139]:
np.vstack((arr1,arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

#  

# stack 2-d matrix horizontally and vertically 

In [140]:
np.random.seed(123)
mat1=np.random.randint(1,10,9).reshape(3,3)
mat2=np.random.randint(11,20,9).reshape(3,3)

In [141]:
mat1

array([[9, 7, 2],
       [7, 9, 8],
       [2, 8, 2]])

In [143]:
mat2

array([[18, 19, 18],
       [12, 14, 12],
       [19, 18, 16]])

In [144]:
np.hstack((mat1,mat2))

array([[ 9,  7,  2, 18, 19, 18],
       [ 7,  9,  8, 12, 14, 12],
       [ 2,  8,  2, 19, 18, 16]])

In [145]:
np.vstack((mat1,mat2))

array([[ 9,  7,  2],
       [ 7,  9,  8],
       [ 2,  8,  2],
       [18, 19, 18],
       [12, 14, 12],
       [19, 18, 16]])

#   

#   

#   

#    

#     

#   Numpy Array vs Python Lists

In [160]:
# Numpy array is faster than list, so more efficient than list

In [161]:
# we can calcilate time to run one line using  %timeit

In [166]:
%timeit 2+3    # avg(mean) time to run this line is 14.7 neno second

14.7 ns ± 1.59 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [173]:
%timeit [i**2 for i in range(1,11)]                # this line took 5.17 µs(micro second) to run

5.17 µs ± 168 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [168]:
# %%timeit is used to check time of cell to run

In [169]:
%%timeit
l=[]
for i in range(1,5):
    l.append(i**2)                                  # this cell took 2.53 µs to run

2.53 µs ± 386 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [170]:
import numpy as np

In [174]:
%timeit np.arange(1,11)**2                   # it took only 2.03 micro sec to run, we can see that num py is more faster than list becase list took 5.17 sec

2.03 µs ± 143 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
